Repository AashaiAvadhani1/FLP-Inventory, pull requests merged in 2022-04, with the labels that each got.

#19 PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#29 Deploy1
  .github/workflows/django.yml
  inventory/forms.py
  inventory/templates/inventory/checkin.html
  inventory/templates/inventory/checkout.html
  inventory/templates/inventory/reports/generate_report.html
  inventory/test/test_additemform.py
  inventory/test/test_additemview.py
  inventory/test/test_editaction.py
  inventory/test/test_generatereportdrive.py
  inventory/test/test_generatereportlocal.py
  inventory/views.py
  requirements.txt
  ~$manage_items.xlsx
Labels: bug, enhancement, Critical, Frontend

#33 Fixed bug in views.checkedout_action where the quantity_left attribute for items should not be negative
  .github/workflows/pylint.yml
  .gitignore
  inventory/templates/inventory/analytics/line_chart.html
  inventory/views.py
Labels: bug

#34 Deployment 2: Recommended Item Button Feature, Database Migration/Mapping, Auto-Calculation Total for Reports
  .gitignore
  inventory/management/commands/trans.py
  inventory/models.py
  inventory/static/images/blanket.png
  inventory/static/images/hygiene_kit.png
  inventory/static/images/pants.png
  inventory/static/images/pjs.png
  inventory/static/images/shirt_icon.jpg
  inventory/static/images/shoes.png
  inventory/static/images/socks.png
  inventory/static/images/stuffed_animal.png
  inventory/static/images/toys.png
  inventory/static/images/underwear.png
  inventory/templates/inventory/checkout.html
  inventory/test/test_map.py
  inventory/views.py
  ~$manage_items.xlsx
Labels: enhancement, Backend, Frontend, database

#37 Added Privacy Policy Page
  flp/urls.py
  inventory/templates/inventory/_navbar.html
  inventory/templates/inventory/about.html
  inventory/templates/inventory/policy.html
  inventory/views.py
Labels: Frontend, security
